baseURL: "https://tadeckar.github.io/assets-docs/"
languageCode: en-us
outputs:
  home: [ "HTML", "RSS", "JSON"]
publishDir: docs
params:
  author: tadeckar
  themeVariant: assets
  disableNextPrev: true
  disableInlineCopyToClipBoard: true
  landingPageURL: "/assets-docs/"
title: CX Assets Wiki
theme: hugo-theme-learn
