baseURL: "https://www-github3.cisco.com/pages/tadeckar/assets-docs/"
languageCode: en-us
outputs:
  home: [ "HTML", "RSS", "JSON"]
publishDir: docs
params:
  author: tadeckar
  themeVariant: assets
  disableNextPrev: true
  disableInlineCopyToClipBoard: true
  landingPageURL: "/pages/tadeckar/assets-docs/"
title: CX Assets Wiki
theme: hugo-theme-learn
